global:
  resolve_timeout: 5m

route:
  receiver: email-notifications
  repeat_interval: 10m
  group_by: [alertname, job]
  group_wait: 30s
  group_interval: 5m

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "your-email@example.com"
        from: "alert@example.com"
        smarthost: "smtp.example.com:587"
        auth_username: "your-email@example.com"
        auth_identity: "your-email@example.com"
        auth_password: "your-email-password"
