global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:29092"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

rule_files:
  - "alert_rules.yml"
