name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "echo 'SSH Connection Successful'"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          ls -la ~/.ssh

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "cd /home/ec2-user/ec2-kafka-deploy && git pull origin main && docker-compose down && docker-compose up -d"
