name: Deploy to EC2

on:
  push:
    branches:
      - main  # Production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Backup Before Deployment
        run: |
          ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          mkdir -p /home/ec2-user/kafka-server/backups
          tar -czf /home/ec2-user/kafka-server/backups/backup-$(date +%F).tar.gz /home/ec2-user/kafka-server
          EOF

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          cd /home/ec2-user/kafka-server
          git pull origin $(git rev-parse --abbrev-ref HEAD)
          cp .env.$(git rev-parse --abbrev-ref HEAD) .env  # Load the correct environment
          docker-compose down
          docker-compose up -d
          EOF
